### PR TITLE
Rename to html

### PR DESCRIPTION
**Pull request by richsalz**
Convert table of contents to nested lists.

Much markup still needs to be changed if this is HTML.

### CODE REVIEW

**Comment by richsalz** [comment]
@nilz, let me know if you want this kind of thing.  The page right now on the IETF website is kinda borked, and I'll work on fixing all the markup as I go through and make editorial changes, too.

**Comment by larseggert** [comment]
I think we were going to retire the html version, since it can be generated from `md` via `pandoc`?

**Comment by richsalz** [comment]
I don't care what the source is (more or less), and I'll install any tools.  I just think the way it currently looks is a horrible thing for newcomers to see (overall amateurish, broken links, etc. etc) and I will fix things about the markup while I do an editing pass.  *Just tell me what to use*

**Comment by nllz** [comment]
@richsalz We indeed retired the html and work in md. What works or does not work I think depends on the CMS that the IETF uses. 

Perhaps @ghwood can have a look at the broken links in the ToC and report back what changes make that work?

Feel free to report other issues on the site version and then we'll try to address those as well.

**Comment by ghwood** [comment]
Just FYI, there are a couple of PRs waiting for action (19 & 23 I think?) that I believe address some of the markdown problems but there is an underlying issue of differing markdown flavors and the strict edition implemented by the CMS that will likely require some hacks to address.

I will indeed have another look at this.

-Greg

**Pull request closed without merging**
