### PR TITLE
Make all BCP and RFC links to rfc-editor

### PR DESCRIPTION
**Pull request by richsalz**
Also fixed word-wrapping in the WG Chairs paragraph, which
I probably should have left alone for this PR.

Update: undid that change.
Fixes: #30

### CODE REVIEW

**Review by larseggert — CHANGES_REQUESTED** [review]
Should use Markdown links instead of <a>

**Comment by richsalz** [comment]
I think we should fix all the content and then patch up the markdown.  See #42

**Review by larseggert — APPROVED** [review]

**Comment by larseggert** [comment]
ACK

**Comment by richsalz** [comment]
ping @nllz   It would be great if we could get the three PR's merged and then post the version on the IETF site.

I know there are more important things going on right now.  Sorry.

**Pull request merged**
